conversation/urls.py
from django.urls import path 

from . import views

app_name = 'conversation'

urlpatterns = [ 
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path 
from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'), 
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'), 
]

dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item' 

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

myMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')), 
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm 
from django.contrib.auth.models import User 

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your e-mail address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from item.models import Category, Item
from .forms import SignupForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    return render(request, 'core/index.html', {
        'items': items,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form' : form
    })

def logout_user(request):
    logout(request)
    return redirect('/')


def index(request):
    items = Item.objects.filter(is_sold=False)
    paginator = Paginator(items, 3)

    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1) 
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, 'core/index.html', {'items': items})

core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
            
        <title>{% block title %}{% endblock %} | myMarketPlace</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    </head>

    <body class="bg-gray-100">
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-white">
            <div class="flex justify-between items-center space-x-3">
                <img src="{% static 'icon.png' %}" width="30" height="30"/>
                <a href="/" class="text-xl font-semibold">myMarketPlace</a>                
            </div>

            <form class="flex" method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-3 px-6 border rounded-xl mr-2" type="text" value="{{ query }}" placeholder="Search for...">

                <button class="px-3 py-2 text-lg font-semibold bg-blue-50 text-white rounded-xl hover:bg-blue-100">🔎</button>
            </form>

            <div class="space-x-3">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                
                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-3 py-3 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">myPage</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-3 py-3 text-lg font-semibold bg-orange-500 text-white rounded-xl hover:bg-orange-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}

            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %} 

{% block content %}
    <div class="px-6 py-12 bg-gray-100 rounded-xl">
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }} zł</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if items.has_previous and items.has_next %}
            <a href="?page={{ items.previous_page_number }}">&laquo; previous </a>
            <a href="?page={{ items.next_page_number }}">| next &raquo;</a>
            </br>
            <a href="?page=1">&nbsp;&nbsp;&nbsp;&nbsp;&laquo; first </a>
            <a href="?page={{ items.paginator.num_pages }}">| last &raquo;</a>
            </br></br>
            {% elif items.has_previous %}
                <a href="?page={{ items.previous_page_number }}">&laquo; previous</a>
            </br>
                <a href="?page=1">&laquo; first</a>
            </br></br>
            {% elif items.has_next %}
                <a href="?page={{ items.next_page_number }}">next &raquo;</a>
            </br>
                <a href="?page={{ items.paginator.num_pages }}">last &raquo;</a>
            </br></br>
            {% endif %}
            <span class="current-page">Page {{ items.number }} of {{ items.paginator.num_pages }}.</span>
        </span>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-orange-500 hover:bg-orange-700 rounded-xl text-white">Submit</button></br></br>
        <a href="{% url 'password_reset' %}" class="px-0 py-2 text-lg font-semibold underline text-blue-950 rounded-xl">Reset Password</a>
    </form>
</div>
{% endblock %}

core/templates/core/password_reset.html
{% extends 'base.html' %}

{% block title %}Forgot Your Password?{% endblock %}

{% block content %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ from.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-orange-500 hover:bg-orange-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}