core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path 
from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'), 
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_user, name='logout'), 
]

dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item' 

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

myMarketPlace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')), 
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required 
from django.shortcuts import render

# Create your views here.

from item.models import Item

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, 'dashboard/index.html', {
        'items': items,
    })

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}

{% block title %}myPage{% endblock %} 

{% block content %}
    <div class="px-6 py-12 flex bg-white rounded-xl justify-between center-items">
        <div>
            <p>Welcome back, <strong>{{ request.user }}</strong>!</p> 
        </div>
        <a href="{% url 'password_reset' %}" class="px-6 py-3 text-lg font-semibold underline text-blue-950 rounded-xl">Reset Password</a>
        <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold underline text-blue-950 rounded-xl">Log out</a>         
    </div>
    <div class="mt-12">
        <h2 class="mb-6 text-2xl text-center">My items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }} zł</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}